#- Storage params -#
spring:
  profiles: tests
  data:
    mongodb:
      database: storage
      host: localhost
      port: 17017
      username: storage
      password: storage

security:
  user:
    name: Unit_Test
    password: password
    role: POET
  oauth2:
    client:
      client-id: developer
      client-secret: develoepr32

eureka.client.enabled: false
