#- Storage params -#
spring:
  data:
    mongodb:
      database: storage
      host: ${DB_HOST}
      port: 27017
      username: storage
      password: storage

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registry-fetch-interval-seconds: 5
